name: rgbt
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.7=h166bdaf_0
  - pip=22.3.1=pyhd8ed1ab_0
  - python=3.9.13=h2660328_0_cpython
  - readline=8.1.2=h0f457ee_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sqlite=3.40.0=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - accelerate==0.32.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blessed==1.23.0
      - blis==0.7.11
      - boto3==1.39.9
      - botocore==1.39.9
      - catalogue==2.0.10
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - click==8.1.8
      - confection==0.1.5
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.11
      - datasets==2.0.0
      - dill==0.4.0
      - einops==0.8.1
      - en-core-web-md==3.4.1
      - fairscale==0.4.0
      - filelock==3.13.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - gpustat==1.1.1
      - hf-xet==1.1.5
      - huggingface-hub==0.24.5
      - idna==3.10
      - importlib-resources==6.5.2
      - iopath==0.1.10
      - jinja2==3.1.3
      - jmespath==1.0.1
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lightgbm==4.6.0
      - lightning-utilities==0.15.2
      - marisa-trie==1.3.1
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.18
      - murmurhash==1.0.13
      - networkx==3.2.1
      - numpy==1.24.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==13.580.82
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.5.5.62
      - packaging==25.0
      - pandas==2.0.3
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - peft==0.11.1
      - pillow==9.1.1
      - portalocker==3.2.0
      - preshed==3.0.10
      - propcache==0.3.2
      - protobuf==6.33.0
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pycocotools==2.0.10
      - pydantic==1.10.24
      - pynvml==11.4.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.21
      - pytorch-pretrained-bert==0.6.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - responses==0.18.0
      - s3transfer==0.13.1
      - safetensors==0.5.3
      - scipy==1.8.0
      - sentencepiece==0.2.1
      - six==1.17.0
      - smart-open==6.4.0
      - spacy==3.4.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - thinc==8.1.12
      - timm==0.6.13
      - tokenizers==0.13.3
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchfile==0.1.0
      - torchmetrics==1.8.2
      - torchscale==0.3.0
      - torchsummary==1.5.1
      - torchvision==0.17.2
      - torchviz==0.0.2
      - torchwisdom==0.0.1
      - tqdm==4.62.3
      - transformers==4.30.0
      - triton==2.2.0
      - typer==0.7.0
      - typing-extensions==4.9.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - wasabi==0.10.1
      - wcwidth==0.2.13
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /root/miniconda3/envs/rgbt
